language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  - SPHINXSEARCH_BUILD=rel22
  - SPHINXSEARCH_BUILD=beta

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update
  - mkdir $HOME/sphinx
  - pushd $HOME/sphinx
  - wget --quiet http://ppa.launchpad.net/builds/sphinxsearch-${SPHINXSEARCH_BUILD}/ubuntu/dists/`lsb_release -cs`/main/binary-amd64/Packages
  - SPHINX_DEB=`grep -m1 Filename Packages | cut -f2 -d' '`
  - wget --quiet -O sphinxsearch.deb http://ppa.launchpad.net/builds/sphinxsearch-${SPHINXSEARCH_BUILD}/ubuntu/${SPHINX_DEB}
  - dpkg -x sphinxsearch.deb .
  - popd

install:
  - composer install

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - cd Tests
  - $HOME/sphinx/usr/bin/searchd -c sphinx.conf
  - cd ..

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - cat Tests/data/searchd.log
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
